### ISSUE TITLE
Extend the ability of gitpod regarding env variables and files

### ISSUE THREAD

**Issue by Derroylo** [Derroylo/gitpod-tool#10]
Gitpod has some basic support for env variables and files. These functions should be extended with the following functions:

- [x] Change the config reader/writer for the new config settings
- [x] Restore simple env variables https://github.com/gitpod-io/gitpod/issues/17580
- [x] Save and restore files with multi line support. https://github.com/gitpod-io/gitpod/issues/10804
- [x] Add the ability to store a whole folder as env variable https://github.com/gitpod-io/gitpod/issues/9284
- [x] Update the documentation

Suggested syntax for .gpt.yml:
````yaml
env:
  vars:
    test: Testvalue
  files:
    auth.json: GPT_AUTH_JSON
````

**Comment by Derroylo** [comment]
All done, docs will be updated before the release of the next alpha version

**Comment by Derroylo** [comment]
Has been implemented in v0.5.0
